import { Geist, Geist_Mono, Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { CartProvider } from "@/utils/context";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const rubixSerif = Rubik({
    variable: "--font-rubik",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={`${rubixSerif.variable}  antialiased`}>
                <CartProvider>
                    <Navbar />
                    {children}
                    <Footer />
                    <Toaster />
                </CartProvider>
            </body>
        </html>
    );
}
